spring.application.name=AnimeTrack

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/jjk_db
spring.datasource.username=postgres
spring.datasource.password=harish

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Increase upload limits for local images
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
